### ISSUE TITLE
[BUG] - Erreur d'indication de professeur absent

### ISSUE THREAD

**Issue by CHALENCON-Yoan** [Merlode11/pronote-bot-discord#5]
Bonjour,
Le bot indique qu'un(e) professeur est absent alors qu'iel ne l'est pas forcément. Je m'explique : s'il y a une modification dans les groupes et/ou la classe qui doit suivre le cours, le/la professeur sera indiqué(e) absent(e) par le bot alors que ce n'est pas le cas. Il en est de même lorsqu'il y a une modification de salle sur un cours.

Dans mon cas :
- Sur les cours d'EPS, une des classes présentes habituellement va être absente pendant plusieurs semaines en raison des stages et cette classe a été supprimée du cours sur les semaines concernées. Le bot considère donc que le professeur qui doit assurer le cours d'EPS pour la classe restante sera absent.
- Sur un cours, il y a un changement exceptionnel de salle et le bot pense là aussi que le professeur sera absent alors que ce n'est pas le cas.

Cela est un peu dérangeant, il faudrait mieux que le bot ne notifie pas de changement pour ces cas là ou alors qu'il indique qu'il y a un changement de salle ou de groupes.

Les screens concernant le cours où la salle a été modifiée :
![image](https://user-images.githubusercontent.com/81905759/199508019-381e1c4b-629c-4e72-9dc8-53686e20cbbf.png)
![image](https://user-images.githubusercontent.com/81905759/199508170-86a048aa-6b5b-47a3-9a0d-ab5454a00849.png)

_Merci d'avance pour la résolution de ce petit bug !_

**Comment by Merlode11** [comment]
Bonjour,

Merci pour le signalement de ce bug. Il faut avouer que ça ne m'était jamais arrivé donc je n'ai jamais eu l'occasion d'avoir le bug.

Est-ce qu'il serait possible d'avoir la requête obtenue lorsque le bot vérifie si le cours est absent ?
Ça pourrait m'aider à corriger le problème.

Merci pour ta coopération !

**Comment by CHALENCON-Yoan** [comment]
Oui, avec plaisir. Simplement, que faut-il que je fasse pour avoir cette requête ?

**Comment by Merlode11** [comment]
Alors, pour cela il faudra un peu modifier le fichier `pronoteSynchronization.js`, présent dans le dossier **`/utils`**:

Dans ce fichier, à la ligne **102**, il y a le début de la vérification pour les profs absents.
Il serait bien de mettre à entre la ligne **107** et **108**, donc sur une nouvelle ligne, le code suivant:
```js
console.log(lesson)
```
Il suffira après de me donner ce qui s'est affiché dans la console une fois la vérification effectuée

**Comment by CHALENCON-Yoan** [comment]
Voici les requêtes :

`{
  id: 'e5c27bdb4406b3e1',
  from: 2022-11-08T14:00:00.000Z,
  to: 2022-11-08T16:00:00.000Z,
  isDetention: false,
  remoteLesson: false,
  status: 'Classe absente',
  hasDuplicate: true,
  isAway: false,
  isCancelled: true,
  color: '#212853',
  subject: 'EDUCATION PHYSIQUE ET SPORTIVE',
  teacher: 'PERRENOUD L.',
  room: null
}
{
  id: 'f19dd57ac11d9d1',
  from: 2022-11-15T14:00:00.000Z,
  to: 2022-11-15T16:00:00.000Z,
  isDetention: false,
  remoteLesson: false,
  status: 'Classe absente',
  hasDuplicate: true,
  isAway: false,
  isCancelled: true,
  color: '#212853',
  subject: 'EDUCATION PHYSIQUE ET SPORTIVE',
  teacher: 'PERRENOUD L.',
  room: null
}
{
  id: '7b4e9d04e20d4570',
  from: 2022-11-18T09:20:00.000Z,
  to: 2022-11-18T11:20:00.000Z,
  isDetention: false,
  remoteLesson: false,
  status: 'Cours annulé',
  hasDuplicate: true,
  isAway: false,
  isCancelled: true,
  color: '#EFE51F',
  subject: 'HISTOIRE-GEOGRAPHIE',
  teacher: 'VEGLIO L.',
  room: '208'
}
{
  id: '3e0254d40d4ad541',
  from: 2022-11-22T14:00:00.000Z,
  to: 2022-11-22T16:00:00.000Z,
  isDetention: false,
  remoteLesson: false,
  status: 'Classe absente',
  hasDuplicate: true,
  isAway: false,
  isCancelled: true,
  color: '#212853',
  subject: 'EDUCATION PHYSIQUE ET SPORTIVE',
  teacher: 'PERRENOUD L.',
  room: null
}
{
  id: '1d551efe8d79b771',
  from: 2022-11-29T14:00:00.000Z,
  to: 2022-11-29T16:00:00.000Z,
  isDetention: false,
  remoteLesson: false,
  status: 'Classe absente',
  hasDuplicate: true,
  isAway: false,
  isCancelled: true,
  color: '#212853',
  subject: 'EDUCATION PHYSIQUE ET SPORTIVE',
  teacher: 'PERRENOUD L.',
  room: null
}`

**Comment by Merlode11** [comment]
Juste une question pour être sûr:
Le cours d'histoire n'aura pas lieu ?

**Comment by CHALENCON-Yoan** [comment]
Si si, il y a juste un changement de salle. Sur Pronote, la salle habituelle apparaît toujours mais il y a l'autre en plus.


2/3 images si ça peut t'aider :

Le cours "normal" d'histoire :
![image](https://user-images.githubusercontent.com/81905759/199594105-d13d0463-572a-49eb-adbe-5847a71afd5e.png)

Le cours où on sera dans une autre salle :
![image](https://user-images.githubusercontent.com/81905759/199594171-8f2bfbd0-c2ed-435c-8584-ef6caf995a9b.png)

C'est vrai que c'est plutôt étrange qu'il apparaisse avec un statu "Cours annulé" dans la requête.
Et même pour les cours de sport, le statu "Classe absente" est indiqué dans la requête mais sur Pronote, il n'y a aucune mention particulière, il y a seulement le groupe absent qui a été retiré.

Un cours d'EPS "normal" :
![image](https://user-images.githubusercontent.com/81905759/199594879-3ca836fc-afc1-477d-a921-0d74c0c477e2.png)

Un des cours quand un des groupes est absent :
![image](https://user-images.githubusercontent.com/81905759/199594949-72b7b3ac-4694-4bcf-aa17-45ddf1c7c110.png)

**Comment by Merlode11** [comment]
Ok ! Très bien !
Merci beaucoup, je pense que ça va résoudre le problème du message alors qu'il y a bien cours

**Comment by Merlode11** [comment]
Le bug a bien été résolu dans la nouvelle version [v5.0.7](https://github.com/Merlode11/pronote-bot-discord/releases/latest).
Merci beaucoup pour ton aide !

**Comment by CHALENCON-Yoan** [comment]
Merci pour la rapidité de la mise à jour @Merlode11.
Cependant, il y a un "i" en trop à "lession" à la ligne 107 du fichier "pronoteSynchronization.js" dans "utils". Ce qui provoque une erreur lors de l'exécution de la commande "/recheck" et empêche l'envoie des Communications et des Modifications de Cours par exemple.

**Comment by Merlode11** [comment]
Oups en effet. Toutes mes excuses de l'erreur, c'est maintenant corriger. 
Maintenant ça devrait être complètement corrigé
